


*   Parámetros Posicionales: Crear una función llamada multiplicar que reciba dos números y devuelva su producto. Probar la función con diferentes pares de números.
*   Parámetros por Defecto: Crear una función llamada bienvenida que reciba un nombre y un mensaje de bienvenida. El mensaje debe tener un valor por defecto de "¡Bienvenido!". Si no se proporciona un mensaje, la función debe usar el valor por defecto. Probar la función proporcionando solo el nombre y con el mensaje.
*   Parámetros Indefinidos (*args): Crear una función llamada calcular_promedio que acepte un número variable de notas (posicionales) y devuelva el promedio de esas notas. Probar la función con diferentes cantidades de notas.

In [ ]:
def multiplicar(num1,num2):
  salida = num1 * num2
  return salida
print(f"resultado : {multiplicar(4,5)}")
print(f"resultado : {multiplicar(6,8)}")

resultado : 20
resultado : 48

In [ ]:
def bienvenida(nombre, bienvenida="¡Bienvenido!"):
  return f"{nombre} {bienvenida}"
print(bienvenida("Jorge"))
print(bienvenida("Gladys","¡Hola!"))

Jorge ¡Bienvenido!
Gladys ¡Hola!

In [ ]:
numeros = list(range(1,11))
numeros

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
def calcular_promedio(*args):
  return sum(args) / len(args)
calcular_promedio(*numeros)

5.5

In [ ]:
numeros1 = list(range(1,30))
prueba2 = calcular_promedio(*numeros1)
prueba2

15.0

>Parámetros de Palabras Clave Indefinidas (**kwargs): Crear una función llamada concatena_info que reciba un nombre y un número indefinido de palabras clave (por ejemplo, edad, ciudad, ocupación) y devuelva un string que combine todos los datos. Probar la función pasando varios pares de clave-valor.

In [ ]:

def concatena_info(nombre, **kwargs):
    resultado = f"Nombre: {nombre}"
    for clave, valor in kwargs.items():
        resultado += f", {clave.capitalize()}: {valor}"

    return resultado
concatena_info("Jorge",edad=56,ciudad="Rosario",Ocupacion="Albañil")

'Nombre: Jorge, Edad: 56, Ciudad: Rosario, Ocupacion: Albañil'

In [ ]:
concatena_info("Gladys",edad=68,ciudad="Cordoba",Ocupacion="Abogada")

'Nombre: Gladys, Edad: 68, Ciudad: Cordoba, Ocupacion: Abogada'

In [ ]:
concatena_info("Victor",edad=33,ciudad="Posadas",Ocupacion="Contador")

'Nombre: Victor, Edad: 33, Ciudad: Posadas, Ocupacion: Contador'

#Actividad 2: Introducción a NumPy y Pandas

>Cargar un csv en Google Colab y visualizar sus primeras filas usando Pandas.

>Repetir el ejercicio anterior con una planilla de Google Sheets.

>Investigá el método para cargar planillas de Excel en Google Colab, utilizando Pandas, y repetí el ejercicio del punto 1.

In [ ]:
import pandas as pd

In [ ]:
file_csv = "sample_data/california_housing_test.csv"

In [ ]:
df = pd.read_csv(file_csv)

In [ ]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [ ]:
file_google = "https://docs.google.com/spreadsheets/d/1re3YjFrah14NwxkVEag0exhsj1UKAW4j24f7OKCb2ec/edit#gid=0"

In [ ]:
csv_url = file_google.replace("/edit#gid=", "/export?format=csv&gid=")

In [ ]:
df_gsheet = pd.read_csv(csv_url)

In [ ]:
df_gsheet.head()

,Compra Comun.,Libro el Faro + T.Matematicas (47.000),Libros + Cuentos (86.050),Solo Libros (67.000),Unnamed: 4,Seña 50%,"$43.025,00",Total,"$86.050,00",Unnamed: 9,Unnamed: 10
0,Ailen,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Rocio,NaN,X,NaN,NaN,Libro/Cuento,Cantidad,Precio,Total,Seña 50 %,Resto contra entrega
2,Ursula,NaN,X,NaN,NaN,El Faro y la Flor 5,22,"25.000,00","550.000,00","275.000,00",NaN
3,Baltazar,NaN,NaN,X,NaN,Tarea de Matematicas 5,22,"22.000,00","484.000,00","242.000,00",NaN
4,Sophi,NaN,X,NaN,NaN,Agil Areas 5 PDL,21,"20.000,00","420.000,00","210.000,00",NaN

In [ ]:
file_excel = "sample_data/bd_ventas_ESP.xlsx"

In [ ]:
pd_excel = pd.read_excel(file_excel)

In [ ]:
pd_excel.head(10)

       ID Fecha_ Pedido Cod_Tienda  id_producto  Qtde  Precio_Unitario
0   AX144    2023-01-15   A1500111         1007    35           630.99
1  AX4456    2023-07-27   A5200100         1007    33           630.99
2  AX2320    2023-08-03   A1500108         1005   132           999.00
3  AX4314    2023-07-04   A1500107         1005    72           999.00
4   AX151    2023-01-15   A1500111         1007    44           630.99
5  AX5161    2023-11-18   A3100104         1007    46           630.99
6  AX2399    2023-08-15   A1500111         1005    64           999.00
7  AX2946    2023-11-12   A1500108         1007    26           630.99
8  AX1141    2023-04-09   A1500110         1007    27           630.99
9   AX370    2023-02-01   A1500111         1005    45           999.00